name: 'doodstream_client_project'
description: 'Doodstream Library for interact with system Api'
version: '0.0.0'
repository: 'https://github.com/azkadev/doodstream_client'
homepage: 'https://github.com/azkadev/doodstream_client'
issue_tracker: 'https://github.com/azkadev/doodstream_client/issues'
documentation: 'https://github.com/azkadev/doodstream_client/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/azkadev'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment: 
  sdk: '^3.2.3'
dependencies: 
  general_lib: '^0.0.41'
  mason_logger: '^0.2.15'
  packagex: '^0.0.58'
  path: '^1.9.0'
  universal_io: '^2.2.2'
  yaml: '^3.1.2'
  yaml_edit: '^2.2.0'
  yaml_writer: '^2.0.0'
dev_dependencies: 
  lints: '^4.0.0'
  test: '^1.24.0'
